[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.6.20", features = ["tracing", "headers", "macros"] }
axum-extra = { version = "0.8.0", features = ["typed-routing"] }

tower = "0.4.13"
tower-http = { version = "0.4.3", features = ["trace", "cors", "auth", "add-extension", "util"] } 
tower-cookies = { version = "0.9.0", features = ["private", "signed"]} 

tokio = { version = "1.34.0", features = ["full"] }

utoipa = { version = "4.0.0", features = ["axum_extras", "chrono", "yaml"] }
utoipa-swagger-ui = { version = "4.0.0", features = ["axum"] }

tracing = "0.1.40"
tracing-subscriber = "0.3.17"

serde = "1.0.192"
serde_derive = "1.0.192"

clap = { version = "4.4.7", features = ["derive", "env"] }

sqlx = { version = "0.7.2", features = ["runtime-tokio", "macros", "migrate", "time", "chrono", "postgres"] }

thiserror = "1.0.50"
anyhow = "1.0.48"

uuid = { version = "1.5.0", features = ["serde"] }
reqwest = "0.11.22"
argon2 = "0.5.2"
time = "0.3.23"
jsonwebtoken = "9.1.0"
