[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
poem = "1.3.58"
poem-openapi = { version = "3.0.5", features = ["time", "swagger-ui"] }
poem-openapi-derive = "3.0.5"

tokio = { version = "1.34.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.17"
serde = "1.0.192"
serde_derive = "1.0.192"

clap = { version = "4.4.7", features = ["derive", "env"] }

sqlx = { version = "0.7.2", features = ["runtime-tokio", "macros", "migrate", "time", "chrono", "postgres"] }

thiserror = "1.0.50"
anyhow = "1.0.48"

reqwest = "0.11.22"
argon2 = "0.5.2"
time = "0.3.23"
jsonwebtoken = "9.1.0"
